### ISSUE TITLE
Instable conection via `kubectl port-forward`

### ISSUE THREAD

**Issue by Stausssi** [kubernetes/kubectl#1525] opened 2023-11-27 08:09 UTC
**What happened**:
After some minutes of forwarding a port from my Pod to both my local machine OR a GitHub Actions Runner, the connection fails with a `Timeout occurred` for both the error and forwarding stream.

Some more context:
I have a set of Python based simulations inside a Pod publishing their state to a Pod-internal MQTT broker.
From my local machine I connect to the MQTT broker and run test-cases validating the published states of the simulations as well as forcing the states to change via inputs to the MQTT broker.
The connection to the Pod deployed in AKS is currently established via `kubectl port-forward`.
In the beginning, it worked without any issues, but as the time goes on more and more test-cases have been added leading to me discovering said timeout problem. The first test-cases always run, but towards the end the test cannot connect to the MQTT broker anymore and the timeout error is printed to the log.

The same behaviour can be observed running the test-cases inside a GitHub Action.

The packages somehow still (incompletely) reach the MQTT broker, since the following messages can be found inside the log:
```
New connection from 127.0.0.1:54128 on port 8883.
Client <unknown> closed its connection.
New connection from 127.0.0.1:57310 on port 8883.
Client <unknown> has exceeded timeout, disconnecting.
```
A successful connection looks like this:
```
New client connected from 127.0.0.1:55312 as {clientName} (p2, c1, k600, u'{userName}').
Client {clientName} disconnected.
```

**What you expected to happen**:
Connection should be stable enough for this use-case or reconnect on error.

**How to reproduce it (as minimally and precisely as possible)**:

1. Pod with MQTT broker (`eclipse-mosquitto`, port 8883 exposed) and container(s) populating the MQTT broker with messages 
2. `kubectl port-forward --namespace {namespace} deployment/{deployment} --address 127.0.0.1 8883`
3. Run local (Python) script:
    1. Connect to MQTT broker via `localhost:8883`
    2. Send and receive messages for a couple of seconds
    3. Disconnect
    4. Loop to 1

**Anything else we need to know?**:

`kubectl port-forward` log:

```
Forwarding from 127.0.0.1:8883 -> 8883
Handling connection for 8883
Handling connection for 8883
E1127 08:17:00.478647   31961 portforward.go:379] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8883->127.0.0.1:52899: write tcp4 127.0.0.1:8883->127.0.0.1:52899: write: broken pipe
Handling connection for 8883
Handling connection for 8883
Handling connection for 8883
E1127 08:19:10.829113   31961 portforward.go:379] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8883->127.0.0.1:52950: write tcp4 127.0.0.1:8883->127.0.0.1:52950: write: broken pipe
E1127 08:20:11.630955   31961 portforward.go:379] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8883->127.0.0.1:52955: write tcp4 127.0.0.1:8883->127.0.0.1:52955: write: broken pipe
Handling connection for 8883
E1127 08:21:17.450436   31961 portforward.go:379] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8883->127.0.0.1:52971: write tcp4 127.0.0.1:8883->127.0.0.1:52971: write: broken pipe
Handling connection for 8883
E1127 08:22:42.655627   31961 portforward.go:379] error copying from remote stream to local connection: readfrom tcp4 127.0.0.1:8883->127.0.0.1:52980: write tcp4 127.0.0.1:8883->127.0.0.1:52980: write: broken pipe
Handling connection for 8883
Handling connection for 8883
Handling connection for 8883
E1127 08:23:17.672735   31961 portforward.go:345] error creating error stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:23:27.766222   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:23:37.835683   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:23:47.832082   31961 portforward.go:345] error creating error stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:23:57.921897   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:24:07.966391   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:24:17.992264   31961 portforward.go:345] error creating error stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:24:28.080960   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:24:38.128261   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
Handling connection for 8883
E1127 08:24:48.132906   31961 portforward.go:345] error creating error stream for port 8883 -> 8883: Timeout occurred
E1127 08:24:58.240984   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
E1127 08:25:08.304346   31961 portforward.go:368] error creating forwarding stream for port 8883 -> 8883: Timeout occurred
E1127 08:31:14.955040   31961 portforward.go:233] lost connection to pod
I1127 08:31:14.955663   31961 connection.go:198] SPDY Ping failed: connection closed
```

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"7ffcdf755d47c73903854cc5955afcdcd8c95225", GitTreeState:"clean", BuildDate:"2023-10-09T14:43:34Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`): MacOS / Ubuntu 22.04 (GitHub Actions Runner)

**Comment by Stausssi** [comment] 2023-12-07 09:40
The issues happens both from AKS to my local computer as well as from AKS to a GitHub Actions runner.
I've tried executing `while true; do nc -vz 127.0.0.1 8883; sleep 1; done` simultaneously to the port-forward, basically connecting to the forwarded port every second. It also does show up as connection attempts in the logs of the MQTT broker.
If I run netcat without actually opening the MQTT connection, it works for >20 minutes without a timeout. Once I start opening the MQTT connection and transferring actual data, both fail after a couple of minutes and every netcat connection attempt will result in a timeout (according to port-forward, netcat reports success). Will get working on a script just handling the MQTT connect / disconnect and see if that runs into the same problem.
Will report back

**Comment by Stausssi** [comment] 2023-12-07 14:46
As it turns out, just connecting and disconnecting via MQTT works fine for longer durations as well, but once I start transferring actual data (e.g. subscribing to topics) the connection seems to drop. I'll see how (if) I can get the networking logs.
In the meantime, it would be nice to know if this can be reproduced on your side. I'm happy to assist

**Comment by Stausssi** [comment] 2023-12-08 13:23
I've tried to reinforce the MQTT connection as much as possible (ensuring there is no data being transferred upon disconnecting, ensure the connection was closed successfully, retrying up to five times if it doesn't work) and it did improve a little bit, however I'm still met with occasional broken pipes, connection reset by peer and ultimately timeouts. Once the connection starts to timeout, there is no way to get it back except for restarting the port-forward.
Furthermore, a continuous ping reports a packet loss of just 0.2% out of over 1200 packets.

Networking logs of the node:
```
12:55:02 containerd[2132]: time="2023-12-08T12:55:02.975417929Z" level=info msg="Executing port forwarding in network namespace \"/var/run/netns/cni-3872189f-e4ce-6f3a-e224-516016054b33\""
12:55:06 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.zwYTA3.mount: Deactivated successfully.
12:55:17 systemd[1]: run-containerd-runc-k8s.io-9a91aef73c2b915ee5b87c5ca54f3f13a157efcbd5d8a15db82d27a6dc5f5b8e-runc.wyJ5nM.mount: Deactivated successfully.
12:55:56 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.vhfIbC.mount: Deactivated successfully.
12:56:23 containerd[2132]: time="2023-12-08T12:56:23.572237559Z" level=info msg="Finish port forwarding for \"6df665e344c81acf24f2ca2dc72030ba398fd8c561ee417ce392dbac02110832\" port 8883"
12:56:28 containerd[2132]: time="2023-12-08T12:56:28.674154595Z" level=info msg="Executing port forwarding in network namespace \"/var/run/netns/cni-3872189f-e4ce-6f3a-e224-516016054b33\""
12:56:36 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.sf2lg7.mount: Deactivated successfully.
12:57:37 systemd[1]: run-containerd-runc-k8s.io-9a91aef73c2b915ee5b87c5ca54f3f13a157efcbd5d8a15db82d27a6dc5f5b8e-runc.fH5ZlV.mount: Deactivated successfully.
12:57:46 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.DBIraN.mount: Deactivated successfully.
12:57:49 containerd[2132]: time="2023-12-08T12:57:49.258633934Z" level=info msg="Finish port forwarding for \"6df665e344c81acf24f2ca2dc72030ba398fd8c561ee417ce392dbac02110832\" port 8883"
12:58:24 containerd[2132]: E1208 12:58:24.332310    2132 httpstream.go:160] (conn=0xc000c546c0, request=5) timed out waiting for streams
12:58:34 containerd[2132]: E1208 12:58:34.332063    2132 httpstream.go:160] (conn=0xc000c546c0, request=6) timed out waiting for streams
12:58:44 containerd[2132]: E1208 12:58:44.353898    2132 httpstream.go:160] (conn=0xc000c546c0, request=7) timed out waiting for streams
12:58:49 python3[1706]: 2023-12-08T12:58:49.342614Z INFO TelemetryEventsCollector ExtHandler Collected 2 events for extension: Microsoft.Azure.Extensions.CustomScript
12:58:54 containerd[2132]: E1208 12:58:54.368464    2132 httpstream.go:160] (conn=0xc000c546c0, request=8) timed out waiting for streams
12:58:56 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.E0PILB.mount: Deactivated successfully.
12:59:04 containerd[2132]: E1208 12:59:04.389702    2132 httpstream.go:160] (conn=0xc000c546c0, request=9) timed out waiting for streams
12:59:14 containerd[2132]: E1208 12:59:14.467623    2132 httpstream.go:160] (conn=0xc000c546c0, request=10) timed out waiting for streams
12:59:24 containerd[2132]: E1208 12:59:24.532220    2132 httpstream.go:160] (conn=0xc000c546c0, request=11) timed out waiting for streams
```
Please note that a new connection attempt was made directly after the "Finish port forwarding..." message (12:56:49), which times out as seen in the next message at 12:58:24

**Comment by AndriyKalashnykov** [comment] 2023-12-19 14:13
> I've tried to reinforce the MQTT connection as much as possible (ensuring there is no data being transferred upon disconnecting, ensure the connection was closed successfully, retrying up to five times if it doesn't work) and it did improve a little bit, however I'm still met with occasional broken pipes, connection reset by peer and ultimately timeouts. Once the connection starts to timeout, there is no way to get it back except for restarting the port-forward. Furthermore, a continuous ping reports a packet loss of just 0.2% out of over 1200 packets.
> 
> Networking logs of the node:
> 
> ```
> 12:55:02 containerd[2132]: time="2023-12-08T12:55:02.975417929Z" level=info msg="Executing port forwarding in network namespace \"/var/run/netns/cni-3872189f-e4ce-6f3a-e224-516016054b33\""
> 12:55:06 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.zwYTA3.mount: Deactivated successfully.
> 12:55:17 systemd[1]: run-containerd-runc-k8s.io-9a91aef73c2b915ee5b87c5ca54f3f13a157efcbd5d8a15db82d27a6dc5f5b8e-runc.wyJ5nM.mount: Deactivated successfully.
> 12:55:56 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.vhfIbC.mount: Deactivated successfully.
> 12:56:23 containerd[2132]: time="2023-12-08T12:56:23.572237559Z" level=info msg="Finish port forwarding for \"6df665e344c81acf24f2ca2dc72030ba398fd8c561ee417ce392dbac02110832\" port 8883"
> 12:56:28 containerd[2132]: time="2023-12-08T12:56:28.674154595Z" level=info msg="Executing port forwarding in network namespace \"/var/run/netns/cni-3872189f-e4ce-6f3a-e224-516016054b33\""
> 12:56:36 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.sf2lg7.mount: Deactivated successfully.
> 12:57:37 systemd[1]: run-containerd-runc-k8s.io-9a91aef73c2b915ee5b87c5ca54f3f13a157efcbd5d8a15db82d27a6dc5f5b8e-runc.fH5ZlV.mount: Deactivated successfully.
> 12:57:46 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.DBIraN.mount: Deactivated successfully.
> 12:57:49 containerd[2132]: time="2023-12-08T12:57:49.258633934Z" level=info msg="Finish port forwarding for \"6df665e344c81acf24f2ca2dc72030ba398fd8c561ee417ce392dbac02110832\" port 8883"
> 12:58:24 containerd[2132]: E1208 12:58:24.332310    2132 httpstream.go:160] (conn=0xc000c546c0, request=5) timed out waiting for streams
> 12:58:34 containerd[2132]: E1208 12:58:34.332063    2132 httpstream.go:160] (conn=0xc000c546c0, request=6) timed out waiting for streams
> 12:58:44 containerd[2132]: E1208 12:58:44.353898    2132 httpstream.go:160] (conn=0xc000c546c0, request=7) timed out waiting for streams
> 12:58:49 python3[1706]: 2023-12-08T12:58:49.342614Z INFO TelemetryEventsCollector ExtHandler Collected 2 events for extension: Microsoft.Azure.Extensions.CustomScript
> 12:58:54 containerd[2132]: E1208 12:58:54.368464    2132 httpstream.go:160] (conn=0xc000c546c0, request=8) timed out waiting for streams
> 12:58:56 systemd[1]: run-containerd-runc-k8s.io-2409317817522182fc68094f2fd2fd1a1efd0f016c79fa3772febd1fb7e8d265-runc.E0PILB.mount: Deactivated successfully.
> 12:59:04 containerd[2132]: E1208 12:59:04.389702    2132 httpstream.go:160] (conn=0xc000c546c0, request=9) timed out waiting for streams
> 12:59:14 containerd[2132]: E1208 12:59:14.467623    2132 httpstream.go:160] (conn=0xc000c546c0, request=10) timed out waiting for streams
> 12:59:24 containerd[2132]: E1208 12:59:24.532220    2132 httpstream.go:160] (conn=0xc000c546c0, request=11) timed out waiting for streams
> ```
> 
> Please note that a new connection attempt was made directly after the "Finish port forwarding..." message (12:57:49), which times out as seen in the next message at 12:58:24

Simon, I may have similar issue while deploying Mosquitto 2.0.18.openssl on minikube and trying to forward 
`kubectl port-forward svc/mosquitto-service -n edge 1883:1883 8883:8883 --address='0.0.0.0'`
Can you share manifests used for Mosquitto deployment (configmap, sts, etc) so i can try to reproduce it as well? Thanks.

**Comment by Stausssi** [comment] 2024-01-03 09:26
My mosquitto deployment is quite basic:
```yaml
- name: mqtt
  image: 'my-custom-eclipse-mosquitto:latest'
  ports:
    - containerPort: 8883
      hostPort: 8883
      protocol: TCP
```

`my-custom-eclise-mosquitto` has the `mosquitto.conf` and already baked into it.

I mainly use the default settings for `mosquitto.conf` except:
- `listener` is set to 8883 with the `socket_domain` restricted to IPv4 only
- `persistence` is turned off
- `allow_anonymous` is false and using a password file baked into the image

**Comment by los93sol** [comment] 2024-06-03 17:40
I'm having similar issues, in my case the connection drops at almost exactly 60s.  I noted that it only happens when I'm running it through my ingress from a remote machine.  If I run on the node itself it does not timeout so I suspect something with ingress-nginx is the culprit, but I've been unable to track it down, set basically every timeout annotation without success.  I also switched over to v 1.30 and enabled port forwarding over websockets and can see it works, but I still get the timeouts.  Anyone have any thoughts or suggestions?

**Comment by ardaguclu** [comment] 2024-06-28 09:00
This seems to be a duplicate of https://github.com/kubernetes/kubectl/issues/1606 and please see this comment https://github.com/kubernetes/kubectl/issues/1606#issuecomment-2149219184. I'm closing this issue and feel free to reopen it, if I'm missing something. Thank you.

/close

**Closed by ardaguclu** 2024-06-28 09:00 UTC
Labels: kind/bug, needs-triage

**Comment by Stausssi** [comment] 2024-07-01 06:00
Thanks for the update! I've subscribed to kubernetes/enhancements#4006 and will update this ticket once I get to testing
