### ISSUE TITLE
Kubectl apply fails when using in-cluster configuration

### ISSUE THREAD

**Issue by erwinvaneyk** [kubernetes/kubectl#761] opened 2019-11-07 08:50 UTC
When using kubectl with an in-cluster configuration, `kubectl apply` seems to fail. I suspect that either the discovery or the dynamic client does not use in-cluster configuration correctly, as it seems to take the default configuration (localhost:8080).

Most other commands, like a `kubectl get pods` run completely fine:
```
$ kubectl -v=7 get pods

I1104 12:39:31.792561     758 merged_client_builder.go:164] Using in-cluster namespace
I1104 12:39:31.792869     758 merged_client_builder.go:122] Using in-cluster configuration
I1104 12:39:31.882210     758 merged_client_builder.go:122] Using in-cluster configuration
I1104 12:39:31.953619     758 merged_client_builder.go:122] Using in-cluster configuration
I1104 12:39:31.954134     758 round_trippers.go:420] GET https://10.96.0.1:443/api/v1/namespaces/mvp-system/pods?limit=500
I1104 12:39:31.954189     758 round_trippers.go:427] Request Headers:
I1104 12:39:31.954237     758 round_trippers.go:431]     Accept: application/json;as=Table;v=v1beta1;g=meta.k8s.io, application/json
I1104 12:39:31.954282     758 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:39:31.954333     758 round_trippers.go:431]     Authorization: Bearer <masked>
I1104 12:39:32.166998     758 round_trippers.go:446] Response Status: 200 OK in 212 milliseconds
```

However, `kubectl apply` fails, as it is trying to discover the api on the default kubernetes uri.
```
$ kubectl -v=7 apply -f /path/to/manifest.yaml

I1104 12:37:59.847345     375 round_trippers.go:420] GET http://localhost:8080/openapi/v2?timeout=5m0s
I1104 12:37:59.847407     375 round_trippers.go:427] Request Headers:
I1104 12:37:59.847523     375 round_trippers.go:431]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I1104 12:37:59.847567     375 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:37:59.945259     375 round_trippers.go:446] Response Status: 404 Not Found in 97 milliseconds
I1104 12:38:00.045321     375 round_trippers.go:420] GET http://localhost:8080/swagger-2.0.0.pb-v1?timeout=5m0s
I1104 12:38:00.045454     375 round_trippers.go:427] Request Headers:
I1104 12:38:00.045516     375 round_trippers.go:431]     Accept: application/json, */*
I1104 12:38:00.045557     375 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:38:00.046392     375 round_trippers.go:446] Response Status: 404 Not Found in 0 milliseconds
I1104 12:38:00.194684     375 merged_client_builder.go:164] Using in-cluster namespace
I1104 12:38:00.251803     375 round_trippers.go:420] GET http://localhost:8080/api?timeout=5m0s
I1104 12:38:00.251840     375 round_trippers.go:427] Request Headers:
I1104 12:38:00.251865     375 round_trippers.go:431]     Accept: application/json, */*
I1104 12:38:00.251892     375 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:38:00.342323     375 round_trippers.go:446] Response Status: 404 Not Found in 90 milliseconds
I1104 12:38:00.345572     375 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1104 12:38:00.345786     375 round_trippers.go:420] GET http://localhost:8080/apis?timeout=5m0s
I1104 12:38:00.345835     375 round_trippers.go:427] Request Headers:
I1104 12:38:00.345851     375 round_trippers.go:431]     Accept: application/json, */*
I1104 12:38:00.345870     375 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:38:00.347964     375 round_trippers.go:446] Response Status: 404 Not Found in 2 milliseconds
I1104 12:38:00.351816     375 request.go:1171] body was not decodable (unable to check for Status): couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
I1104 12:38:00.351863     375 cached_discovery.go:125] skipped caching discovery info, no groups found
F1104 12:38:01.313925     375 helpers.go:114] unable to recognize "/path/to/manifest.yaml": no matches for kind "Namespace" in version "v1"
```

The environment and versions used (also tested with kubectl client v1.15.3):
```
$ env

CONTROLLER_MANAGER_METRICS_SERVICE_PORT=tcp://10.104.99.150:8443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/
HOME=/root
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.96.0.1
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/env

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

As a temporary workaround, I constructed an kubeconfig file (`incluster.kubeconfig` in the example below) from the in-cluster configuration, which works. This seems to indicate that the bug is related to how incluster configuration is handled.

```
$ kubectl -v=7 apply -f /path/to/manifest.yaml --request-timeout=5m0s --kubeconfig /tmp/incluster.kubeconfig
 
I1104 12:50:43.359625    2710 loader.go:375] Config loaded from file:  /tmp/incluster.kubeconfig
I1104 12:50:43.360777    2710 round_trippers.go:420] GET https://10.96.0.1:443/openapi/v2?timeout=5m0s
I1104 12:50:43.360835    2710 round_trippers.go:427] Request Headers:
I1104 12:50:43.360878    2710 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:50:43.360901    2710 round_trippers.go:431]     Authorization: Bearer <masked>
I1104 12:50:43.360952    2710 round_trippers.go:431]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I1104 12:50:43.474005    2710 round_trippers.go:446] Response Status: 200 OK in 112 milliseconds
I1104 12:50:44.456704    2710 merged_client_builder.go:164] Using in-cluster namespace
I1104 12:50:44.461231    2710 round_trippers.go:420] GET https://10.96.0.1:443/api/v1/namespaces/foobar?timeout=5m0s
I1104 12:50:44.461329    2710 round_trippers.go:427] Request Headers:
I1104 12:50:44.461370    2710 round_trippers.go:431]     Accept: application/json
I1104 12:50:44.461407    2710 round_trippers.go:431]     User-Agent: kubectl/v1.16.2 (linux/amd64) kubernetes/c97fe50
I1104 12:50:44.461446    2710 round_trippers.go:431]     Authorization: Bearer <masked>
I1104 12:50:44.535927    2710 round_trippers.go:446] Response Status: 200 OK in 74 milliseconds
namespace/foobar unchanged
```

If this is an actual issue (and not a mistake from my side), I would be happy to contribute a patch myself, but could use some pointers where to look. :)

**Comment by zwwhdls** [comment] 2019-11-26 04:05
Hi @erwinvaneyk ,

I can't reproduce this, can you give a more detailed way?

**Comment by eddiezane** [comment] 2020-01-22 17:55
@erwinvaneyk gentle bump on a reproducible case

**Comment by soltysh** [comment] 2020-02-19 17:53
Closing due to age. Feel free to re-open with new insights.
/close

**Closed by soltysh** 2020-02-19 17:53 UTC
Labels: area/kubectl, kind/bug, priority/P1, sig/cli
