### ISSUE TITLE
Help to avoid accidental deletion of persistent volumes

### ISSUE THREAD

**Issue by m-dm** [kubernetes/kubectl#1573] opened 2024-03-14 11:05 UTC
Hi, 

today I mistakenly ran this command:

`kubectl delete pv -n redacted --all`

instead of `kubectl delete pvc -n redacted --all`

so just by skipping a key and of course, not enough attention, bad luck, etc.. I got myself into a sticky situation.

After fixing my mistake, i thought that could be useful that kubectl returns an error if a namespace is specified in a command related to a non-namespaced resource, like in my case.

Please forgive me if I'm wrong, as you saw i'm still a kubernetes novice. And also please sorry my bad english.

Thanks
Regards

**Comment by ardaguclu** [comment] 2024-03-14 11:12
This is well-known issue and duplicate of https://github.com/kubernetes/kubectl/issues/1365. Unfortunately, we can't change the default behavior as it breaks older clusters. Suggested workaround is using `--interactive` flag in delete command https://github.com/kubernetes/kubectl/issues/1365#issuecomment-1422998174

**Comment by m-dm** [comment] 2024-03-14 12:32
duplicate of https://github.com/kubernetes/kubectl/issues/1365

**Closed** 2024-03-14 12:31 UTC
Labels: kind/feature, needs-triage
