### ISSUE TITLE
`kubectl get events --watch` prints other resource information instead of events

### ISSUE THREAD

**Issue by goutamtadi1** [kubernetes/kubectl#767] opened 2019-11-13 16:49 UTC
```
LAST SEEN   TYPE      REASON                     OBJECT                                                  MESSAGE
15s         Normal    Pulled                     pod/greenplum-operator-5575c9fc9d-kx92d                 Container image "greenplum-operator:latest" already present on machine
14s         Normal    Created                    pod/greenplum-operator-5575c9fc9d-kx92d                 Created container greenplum-operator
NAME                                               AGE
my-greenplum-pgdata-segment-a-0.15d6831e50a3f780   0s
master-0.15d6831ea907f0c3                          0s
segment-a-0.15d6831ea99bb164                       0s
master-0.15d6831ee11db490                          0s
master-0.15d6831ee4b8e843                          0s
master-0.15d6831ef4e342f6                          0s
segment-a-0.15d6831efe35790b                       0s
segment-a-0.15d6831f02d2ea06                       0s
segment-a-0.15d6831f1062c08d                       0s
```

OS: MacOS
K8s: Minikube
Kubectl version: 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:41:55Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.5", GitCommit:"0e9fcb426b100a2aea5ed5c25b3d8cfbb01a8acf", GitTreeState:"clean", BuildDate:"2019-08-05T09:13:08Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by paranoidsp** [comment] 2020-01-07 12:35
Duplicate of #734

**Comment by soltysh** [comment] 2020-01-22 17:47
Closing as duplicate.
/close

**Closed by soltysh** 2020-01-22 17:47 UTC
