### ISSUE TITLE
coloring option in kubectl command output

### ISSUE THREAD

**Issue by jainpratik163** [kubernetes/kubectl#1295] opened 2022-10-05 10:30 UTC
**What would you like to be added**:
we want to have some coloring output when we run kubectl command instead of showing output as in plain color.

**Why is this needed**:
it will help us to identify things and also in case of an error we should show output in red color.

**Comment by ardaguclu** [comment] 2022-10-05 10:55
This looks like a duplicate of https://github.com/kubernetes/kubectl/issues/524.

**Closed** 2022-10-12 16:20 UTC
Labels: kind/feature, needs-triage
