### ISSUE TITLE
Enhance output message in kubectl command with filters

### ISSUE THREAD

**Issue by sauravmndl** [kubernetes/kubectl#1522] opened 2023-11-23 12:41 UTC
**What would you like to be added**:
when execute some command like this with filter
`kubectl get pods -n mynamesapce --field-selector status.phase=Pending -o wide`

and returns no output like 

`No resources found in mynamesapce namespace.`

This indicates nothing found in the namesapce.  But actually with provided filter no resource found. Resources are there.

**Why is this needed**:

1.  Msg like this will be better `No resources found in mynamesapce namespace with applied filter.` or `No resources found in mynamesapce namespace with applied conditions.`
2. If it is specific for namespace `in mynamesapce namespace.` then should clearly call out with condition/filter.

**Comment by ardaguclu** [comment] 2023-11-23 12:46
This seems duplicate of https://github.com/kubernetes/kubectl/issues/1485, I'd prefer closing this to better manage in one issue. Feel free to reopen it, if I'm missing something. Thanks.

/close

**Closed** 2023-11-23 12:46 UTC
Labels: kind/feature, needs-triage

**Comment by sauravmndl** [comment] 2023-11-23 12:47
It is not duplicate of https://github.com/kubernetes/kubectl/issues/1485
