### ISSUE TITLE
kubectl version --client=false tries to contact server and fails

### ISSUE THREAD

**Issue by joaocc** [kubernetes/kubectl#814] opened 2020-02-02 18:21 UTC
This behaviour was not present a few versions of kubectl ago (as it has been used in a set of automation scripts in the past).
Basically, from our understanding, `kubectl version --client=false` should not try to contact any server and should return the version of the local kubectl install.
Happens on mac and alpine
```
$kubectl version --client=false
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:47Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by seans3** [comment] 2020-02-19 17:23
The actual flag is `--client` without a value (ie. NOT `--client=false`). This is not a bug--closing.

/close

**Closed by seans3** 2020-02-19 17:23 UTC

**Comment by apelisse** [comment] 2020-02-19 19:29
It is indeed a boolean, but `--client=false` means the opposite of what you want. You want `--client=true` to only show client information. @zhouya0 has created a PR to clarify the help string.
