### ISSUE TITLE
Spinning beachball of death

### ISSUE THREAD

**Issue by mcandre** [kubernetes/kubectl#1067] opened 2021-06-01 16:19 UTC
**What happened**:

kubectl regularly locks up my Mac.

**What you expected to happen**:

Not that.

**How to reproduce it (as minimally and precisely as possible)**:

Use really any kubectl command, such as `kubectl get namespace`. On my Mac, I can't even run terminal commands in other Terminal.app tabs until the kubectl command terminates. I get a spinning beachball for my mouse cursor. My computer becomes unusable for several minutes.

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-21T20:21:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: EKS
- OS (e.g: `cat /etc/os-release`):

macOS 11.3 Big Sur

**Comment by brianpursley** [comment] 2021-06-01 17:07
Possible duplicate of https://github.com/kubernetes/kubectl/issues/1053

@mcandre does it happen always, or just frequently but random?

Also, do you have an M1 Mac?

Anything in system logs during that time?

**Comment by eddiezane** [comment] 2021-06-01 23:56
Let's track this on the other issue.

@mcandre please respond to open questions there to help us debug.

/close
/triage duplicate

**Closed** 2021-06-01 23:57 UTC
Labels: kind/bug, needs-triage, triage/duplicate
