### ISSUE TITLE
`kubectl diff` and `kubectl apply --dry-run=server` fail when simultaneously creating `Role` and `RoleBinding`

### ISSUE THREAD

**Issue by armingerten** [kubernetes/kubectl#1575] opened 2024-03-19 09:50 UTC
**What happened**:
When running `kubectl diff` or `kubectl apply` with the `--dry-run=server` option on a manifest file containing both `Role` and `RoleBinding`, one will receive a `NotFound` error message:

Error message for `apply --dry-run=server`:
```sh
Error from server (NotFound): error when creating "manifests.yml": roles.rbac.authorization.k8s.io "pod-reader" not found
```
Error message for `diff`:
```sh
Error from server (NotFound): roles.rbac.authorization.k8s.io "pod-reader" not found
```

Applying the resources with `kubectl apply -f manifests.yml` however works successfully as long as `RoleBinding` manifests appear after `Role` manifests within the manifest file.

**What you expected to happen**:
The behavior between `apply`, `apply --dry-run=server` and `diff` must be consistent. 
It should be possible to apply, dry-run or diff manifest files containing roles and rolebinding that are being / would be created in the process.

**How to reproduce it (as minimally and precisely as possible)**:
Run one of the following commands:
- `kubectl apply -f manifests.yml -n my-namespace --dry-run=server`
- `kubectl diff -f manifests.yml -n my-namespace`

on `manifests.yml` with the following content:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: ['']
  resources: ['pods']
  verbs: ['get', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: test-serviceaccount
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes server version: `v1.27.7`
- Kubernetes client versions: I tested with: `v1.27.7`, `v1.27.12`, `v1.28.8` and `v1.29.3`

**Comment by ardaguclu** [comment] 2024-03-19 12:23
I think, this is similar (or even duplicate) of this issue https://github.com/kubernetes/kubectl/issues/1331 and I don't think that there is any way to overcome this.

**Comment by armingerten** [comment] 2024-03-20 07:49
Thanks for the quick reply.
Yes, I can see the problem that both issues are sharing. From a user's perspective it is very confusing though that a dry run of a specific operation fails while the actual operation (i.e. applying the manifest file) is successful.

One possible mitigation of this issue could be some sort of switch to turn off the validation for resources referenced by other resources. I don't know if this can be propagated to the api server somehow?

**Comment by tewfik-ghariani** [comment] 2024-03-20 09:00
It is worth highlighting that the `diff` command does not complain about a non-existing `ServiceAccount` resource even though it is referenced in the `RoleBinding`

**Comment by ardaguclu** [comment] 2024-03-28 06:53
> Thanks for the quick reply. Yes, I can see the problem that both issues are sharing. From a user's perspective it is very confusing though that a dry run of a specific operation fails while the actual operation (i.e. applying the manifest file) is successful.
> 
> One possible mitigation of this issue could be some sort of switch to turn off the validation for resources referenced by other resources. I don't know if this can be propagated to the api server somehow?

As mentioned in here https://github.com/kubernetes/kubectl/issues/1331#issuecomment-1338227246, without significant changes on API server, we can't achieve this. Besides, I'm adding a reference to my previous detailed investigation https://github.com/kubernetes/kubectl/issues/1331#issuecomment-1328872451. 

To sum up, we are aware of the issue but it is working by design and I'm closing this as a duplicate;
/close

**Closed by ardaguclu** 2024-03-28 06:53 UTC
Labels: kind/bug, needs-triage
