### ISSUE TITLE
kubectl can output object as JSON, but not as YAML.

### ISSUE THREAD

**Issue by Ark-kun** [kubernetes/kubectl#774] opened 2019-11-25 23:02 UTC
YAML is a superset of JSON, so everything that can be output as JSON can be output as YAML (for example, it can be the same serialized JSON string).

However, `kubectl` fails to output some objects as YAML.

```
$ kubectl get wf load-predict-pipeline-logreg-d4gbj --output yaml
error: error converting JSON to YAML: %!(EXTRA *errors.errorString=yaml: control characters are not allowed)

```
```
$ kubectl get wf load-predict-pipeline-logreg-d4gbj --output json
...
                    "parameters": [
                        {
                            "name": "preprocessor-x-output",
                            "value": "�\u0003cpandas.core.frame\nDataFrame\nq\u0000)�q\u0001}q\u0002(X\u0005\u0000\u0000\u0000_dataq\u0003cpandas.core.internals.managers\nBlockManager\nq\u0004)�q\u0005(]q\u0006(cpandas.core.indexes.base\n_new_Index\nq\u0007cpandas.core.indexes.base\nIndex\nq\u0008}q\t(X\u0004\u0000\u0000\u0000dataq\ncnumpy.core.multiarray\n_reconstruct\nq\u000bcnumpy\nndarray
...
```

**Comment by eddiezane** [comment] 2020-01-22 17:42
@Ark-kun can you please provide a reproducible config?

**Comment by brianpursley** [comment] 2020-02-14 15:20
Hi @Ark-kun Can you provide a reproducible example and the version of kubectl you are using by running `kubectl version`?

**Comment by soltysh** [comment] 2020-02-19 17:49
Closing since the author did not respond. Feel free to reopen if you have more insights. 
/close

**Closed by soltysh** 2020-02-19 17:49 UTC
Labels: area/kubectl, kind/bug, priority/P2, sig/cli
