### ISSUE TITLE
kubectl port-forward drops connection after a certain amount of time

### ISSUE THREAD

**Issue by anishjayavant** [kubernetes/kubectl#1490] opened 2023-09-22 15:40 UTC
**What happened**:
kubectl port-forward appears to drop the connection to the backend pod after a set of period of time, usually between 5 and 10 minutes.  This has been observed in our environment since a recent upgrade from Kubernetes version 1.21 to 1.25.  The CRI implementation was changed from Docker to containerd

**What you expected to happen**:
The port-forward connection should stay alive end to end without any issues.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start a port-forwarding session to a pod that serves HTTP

```bash
➜  dev date
Fri Sep 22 11:28:18 EDT 2023
➜  dev k port-forward pod-0 8080:30000 -n dev-ns
Forwarding from 127.0.0.1:8080 -> 30000
Forwarding from [::1]:8080 -> 30000
```
2. Run curl against one of this backend's endpoints and verify the result.  This works for about ~5-10 mins.
```bash
➜  dev curl -s http://localhost:8080/v1beta1/users/1 | jq .user.id
"1"
```
<img width="1715" alt="image" src="https://github.com/kubernetes/kubectl/assets/36860630/0eb94a2a-eea8-4578-bc0c-ee1386b42116">

3. The port-forward connection appears to have been dropped after a few minutes, as the curl to localhost starts reporting an empty reply.  Note that the session is still open on localhost, but most likely has suffered a connection reset somewhere within the cluster.
```bash
curl -s --show-error http://localhost:8080/v1beta1/users/1 | jq .user.id
curl: (52) Empty reply from server
```
<img width="1756" alt="image" src="https://github.com/kubernetes/kubectl/assets/36860630/f682e44d-1f24-4966-95d1-9d934a45d085">

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```bash
➜  kubectl ./kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.14", GitCommit:"a5967a3c4d0f33469b7e7798c9ee548f71455222", GitTreeState:"clean", BuildDate:"2023-09-13T09:12:09Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.13", GitCommit:"5244794d27b4cc68290bc496b00e248857ac8b47", GitTreeState:"clean", BuildDate:"2023-08-23T23:54:36Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
We deploy our Kubernetes cluster on Amazon EC2; this is not an EKS cluster. 
Control-plane nodes: Various EC2 shapes in the m5 family, ranging from m5.2xlarge to m5.16xlarge
Worker node where this pod is scheduled: m5.16xlarge
- OS (e.g: `cat /etc/os-release`):
Client OS: Mac OS Ventura 13.5, Apple M1 Pro Chip, 16GB RAM
Server OS: 
```bash
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by ardaguclu** [comment] 2024-06-28 13:04
I believe this is duplicate of https://github.com/kubernetes/kubectl/issues/1525#issuecomment-2196452123 and we can close this. If this is not the same case, feel free to reopen it. Thank you.

/close

**Closed by ardaguclu** 2024-06-28 13:04 UTC
Labels: kind/bug, lifecycle/rotten, needs-triage
