### ISSUE TITLE
show warning when trying to get resources of a namespace which doesn't exit

### ISSUE THREAD

**Issue by RinkiyaKeDad** [kubernetes/kubectl#1493] opened 2023-09-27 14:56 UTC
**What would you like to be added**:

- Right now, if I run `kubectl get pods -n blahblah` and the `blahblah` namespace doesn't exist, it will say "No resources found in blahblah namespace." I think a more appropriate message would be saying that the namespace doesn't exist.

<img width="964" alt="Screenshot 2023-09-27 at 8 26 28 PM" src="https://github.com/kubernetes/kubectl/assets/56963264/964642c0-9e26-4da1-881f-bc887640faf8">

**Why is this needed**:
- Would help make debugging easier in case of typos.

**Comment by ardaguclu** [comment] 2023-09-27 15:00
This is a duplicate of https://github.com/kubernetes/kubectl/issues/1485

**Comment by ardaguclu** [comment] 2023-09-29 09:40
I'm closing, since this is a duplicate as mentioned above;

/close

**Closed by ardaguclu** 2023-09-29 09:40 UTC
Labels: kind/feature, needs-triage
