### ISSUE TITLE
`kubectl api-resources --namespace` incorrect output

### ISSUE THREAD

**Issue by secnum** [kubernetes/kubectl#1513] opened 2023-11-02 13:54 UTC
**What happened**: 

- `kubectl api-resources --namespace=true` should return only namespaced resources but both namespaced and non-namespaced resources are displayed.

- `kubectl api-resources --namespace=false` should return only non-namespaced resources but both namespaced and non-namespaced resources are displayed.

**What you expected to happen**:

The correct filter on resources displayed should be applied.

**How to reproduce it (as minimally and precisely as possible)**:

Type the above commands in a shell.

**Anything else we need to know?**:

Suggestions for improvement:

- ~~Change~~ ~~`--namespace`~~ ~~by~~ ~~`--namespaced`~~.
- `kubectl api-resources --namespace` without argument could return only namespaced resources and not an error. 

**Environment**:
- Kubernetes client and server versions (use `kubectl version`): 1.28.3 (both)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04.3 LTS (ARM)

**Comment by Ritikaa96** [comment] 2023-11-10 06:32
> Suggestions for improvement:
> 
> * Change `--namespace` by `--namespaced`.
> * `kubectl api-resources --namespace` without argument could return only namespaced resources and not an error.
> 
> **Environment**:
As per my observation we already have `kubectl api-resources --namespaced ` command and `--namespace ` alone doesn't work.
I'll suggest running `kubectl api-resources --namepsaced=false` the output is correct.

**Comment by Ritikaa96** [comment] 2023-11-10 06:40
Here is some output sample i got :
`kubectl api-resources --namespaced=false`
![nsfalse](https://github.com/kubernetes/kubectl/assets/52399571/99f06daa-ac25-4951-b8d0-23b7d17ff74f)

`kubectl api-resources --namspaced=true`
![nstrue](https://github.com/kubernetes/kubectl/assets/52399571/82e5dd11-bcb7-4450-a1d7-f00ec5ee895a)

**Comment by Ritikaa96** [comment] 2023-11-10 06:43
`kubectl api-resources --namspace=true|false` shows all resources and that is definitely a bug , which should be resolved.
I will be happy to help in case the triage is accepted.
Although I'd like to see you try the `--namespaced` command and rewrite the title of this bug.

**Comment by secnum** [comment] 2023-11-10 08:09
> Although I'd like to see you try the `--namespaced` command and rewrite the description of this bug.

`kubectl api-resources --namespaced=<true|false>` works properly.

**Comment by ardaguclu** [comment] 2023-11-10 08:14
From the all the conversations above;

```
kubectl api-resources --namespace=true
Works as expected
```
```
kubectl api-resources --namespace=false
works as expected
```
```
kubectl api-resources --namespace
is expected to fail but behaves like --namespace=true
```

If my summary above is correct, there is no bug. Because all the boolean commands in kubectl without any value specified refers to **true**. `--namespace` denotes to `--namespace=true`

**Comment by secnum** [comment] 2023-11-10 08:19
@ardaguclu 

- `kubectl api-resources --namespace=true` and `kubectl api-resources --namespace=false` these commands do not filter the output correctly (all objects are displayed),
- `kubectl api-resources --namespace` fails.

**Comment by ardaguclu** [comment] 2023-11-10 08:21
Sorry I was talking about the `--namespaced` flag(change all the flags on my previous comment with this). Apparently, there is no `--namespace` flag.

**Comment by ardaguclu** [comment] 2023-11-10 08:34
Thanks @secnum. I'm going to investigate this deeper to check that there is a bug or not;
/assign
/triage accepted
/priority backlog

**Comment by ardaguclu** [comment] 2023-11-10 10:17
In kubectl, `--namespace` (i.e. `-n`) is added to all the commands just like `--kubeconfig`. A few commands don't actually use it, such as `explain` or in our case `api-resources`, and setting or not this flag does not make any difference for these commands.

This is the help text of `kubectl api-resources`;
```
$ ./_output/bin/kubectl api-resources --help
Print the supported API resources on the server.

Examples:
  # Print the supported API resources
  kubectl api-resources
  
  # Print the supported API resources with more information
  kubectl api-resources -o wide
  
  # Print the supported API resources sorted by a column
  kubectl api-resources --sort-by=name
  
  # Print the supported namespaced resources
  kubectl api-resources --namespaced=true
  
  # Print the supported non-namespaced resources
  kubectl api-resources --namespaced=false
  
  # Print the supported API resources with a specific APIGroup
  kubectl api-resources --api-group=rbac.authorization.k8s.io

Options:
    --api-group='':
	Limit to resources in the specified API group.

    --cached=false:
	Use the cached list of resources if available.

    --categories=[]:
	Limit to resources that belong to the specified categories.

    --namespaced=true:
	If false, non-namespaced resources will be returned, otherwise returning namespaced resources by default.

    --no-headers=false:
	When using the default or custom-column output format, don't print headers (default print headers).

    -o, --output='':
	Output format. One of: (wide, name).

    --sort-by='':
	If non-empty, sort list of resources using specified field. The field can be either 'name' or 'kind'.

    --verbs=[]:
	Limit to resources that support the specified verbs.

Usage:
  kubectl api-resources [flags] [options]

Use "kubectl options" for a list of global command-line options (applies to all commands).
```

As opposed to `--namespaced` which is a special flag to api-resources command, as you can see, `--namespace` is not in that list and there is no point of using it(if namespace flag is in the help text, that would be definitely a bug).

Consequently, when you pass --namespace flag, command simply drops it and prints the same output of `kubectl api-resources`.

I'd prefer closing this as not a bug. Feel free to re-open it, if I'm missing something.

/close

**Closed** 2023-11-10 10:17 UTC
Labels: kind/bug, priority/backlog, triage/accepted
