### ISSUE TITLE
Kubectl allows unknown flag `-n` when querying resources not linked to namespaces

### ISSUE THREAD

**Issue by JMQuill** [kubernetes/kubectl#1526] opened 2023-11-28 15:50 UTC
**What happened**:
When running a command using the namespace flag such as `kubectl get pv -n {namespace}` all PVs are returned from the cluster

**What you expected to happen**:
An error such as `Unknown flag -n for resource type PersistentVolume`

**How to reproduce it (as minimally and precisely as possible)**:

1.  Run `kubectl get pv -n {namespace}` 
2.  Inspect output and see that all PVs from cluster are returned

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Mac OS 14.1 (23B74)

**Comment by tamilselvan1102** [comment] 2023-11-30 05:09
PVs are not scoped to any namespace.
For ref check [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#not-all-objects-are-in-a-namespace)

**Comment by tamilselvan1102** [comment] 2023-11-30 05:16
To see more about k8s resources are/aren't in a namespace, use following comments 

**resources in namespace**
&nbsp;&nbsp;&nbsp; kubectl api-resources --namespaced=true

**Resources not in namespace**
&nbsp;&nbsp;&nbsp; kubectl api-resources --namespaced=false

**Comment by ardaguclu** [comment] 2023-11-30 11:46
kubectl get command can return multiple resources with a mixture of namespaced and non-namespaced ones. That's why, not returning unknown flag for `-n` is the expected behavior even when the resource is non-namespaced resource to let `kubectl get pv,pvc -n test` return something.

I understand the inconvenience in here but I doubt that we can change this behavior.

**Comment by ardaguclu** [comment] 2023-12-22 13:33
I think, we can close this one because it is duplicate as well as designed by that way;

/close

**Closed** 2023-12-22 13:33 UTC
Labels: kind/bug, needs-triage
