### ISSUE TITLE
Add labels to pod created via kubectl debug

### ISSUE THREAD

**Issue by Indresh-Prakash** [kubernetes/kubectl#1364] opened 2023-02-05 15:47 UTC
**What would you like to be added?**
Currently when a pod is brought up using kubectl debug command, labels from existing pod are not copied to pod brought up by kubectl debug. Any way we can create debug pod with required labels via kubectl debug command . Something like below

kubectl debug -it pod_name --copy-to debug_pod --share-processes --image busybox: --label "app=demo" 

**Why is this needed?**
There are some apps which checks whether a pod has particular label present or not. Since kubectl debug creates a pod that doesn't inherit labels, this is resulting in crashloopbackoff for the actual container that is meant to be debugged

**Comment by Indresh-Prakash** [comment] 2023-02-05 19:34
> Although it is intentional, I think it would be beneficial to introduce a flag to keep labels(only work for `--copy-to`). That request can also be extended to keeping annotations as well.
> 
> /transfer kubectl

Thanks @ardaguclu. Although like @liggitt suggested , having all labels transferred to debug pod, the traffic may get routed to it which could be dangerous . 


Instead a feature where there is an option to pass specific labels manually to kubectl debug command would be great. I believe that would ensure only labels required for app to come up in debug pod would be added

**Comment by sftim** [comment] 2023-02-07 00:16
I don't know about copying existing labels, but a _new_ registered label to mark debug pods could be useful.

**Comment by krishnanandnb** [comment] 2023-02-07 04:55
+1 to new label to mark debug pods

**Comment by Indresh-Prakash** [comment] 2023-02-07 12:28
Another usecase where we could see issue in --copy-to mode is, this impacts setting ENV variables as well in debug pod yaml. Attaching sample for reference
    env:
        - name: Region
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['Region']
Since env variables are dependent on labels in above case, we may not see correct value assigned to it

**Comment by ardaguclu** [comment] 2023-02-09 07:09
@verb what is your opinion about this?. Thanks.

**Comment by raffis** [comment] 2023-02-10 12:12
I run into the same issue (https://github.com/kubernetes/kubernetes/issues/115679), in my case the debug clone was not useful because all network traffic was blocked as it has not the same labels as the pod I wanted to sniff.

Happy to provide a pr to label the clone on the fly if this is a wanted feature.

**Comment by verb** [comment] 2023-02-10 15:29
Indeed we strip labels by design to be "safe by default", but there are several interesting use cases here.

**Crashloop from missing labels**: That's not something we anticipated. @Indresh-Prakash was this because of the broken label reference in env that you mentioned, or something else?

**Missing environment variable**: That's interesting. Maybe we shouldn't stripped labels that are referenced by other fields. There's no way to know if that label was used for traffic assignment, though, so this might not be safe by default.

**Adding a new label**: I like this idea. It seems useful to be able to match for pods created/modified by `kubectl debug`. @sftim were you thinking of an automatic static label or something user modifiable?

**network traffic blocked**: This is working as designed. The intention here was that one would established a debug session and the add the labels that deliver traffic. @raffis  Does this not work?

There are a lot of good ideas here, but I think we have to give the UI some thought to avoid flag creep.

**Comment by sftim** [comment] 2023-02-10 15:32
> @sftim were you thinking of an automatic static label or something user modifiable?

The key should be fixed (maybe an option to disable it, though I can't see why you'd need it). The value could either be `"true"` or some relevant detail.

**Comment by raffis** [comment] 2023-02-10 15:59
> network traffic blocked: This is working as designed. The intention here was that one would established a debug session and the add the labels that deliver traffic. @raffis Does this not work?

Sure I can label it afterwards, but it's annoying. Also a user would need to exactly know which labels are needed. (Or just add all labels from the origin pod).
I'm starting to think that a flag which would copy all the labels is the preferred solution. There are various scenarios where all labels are wanted (but it should not be default).

**Comment by ardaguclu** [comment] 2023-02-10 16:15
> > network traffic blocked: This is working as designed. The intention here was that one would established a debug session and the add the labels that deliver traffic. @raffis Does this not work?
> 
> Sure I can label it afterwards, but it's annoying. Also a user would need to exactly know which labels are needed. (Or just add all labels from the origin pod). I'm starting to think that a flag which would copy all the labels is the preferred solution. There are various scenarios where all labels are wanted (but it should not be default).

I agree to @raffis. Keeping labels and even annotations via some kind of flags might be really useful for some cases. As @verb stated, we need to prevent flag creep and only to add required ones. In my opinion, these would be useful.

**Comment by Indresh-Prakash** [comment] 2023-02-10 16:34
@verb ENV variable issue and  Crashloopback from missing labels are different

For Crashloopback issue, the app checks whether a label is present or not before proceeding with actual application logic. SInce labels are not present in debug pod, this is resulting in crashloopback as the app is expecting particular label to be present

**Comment by ardaguclu** [comment] 2023-05-18 11:08
Thanks to the participants for dropping their comments.

Rather than introducing a specific way to just modify labels, we need a generic way to customize debug pods in terms of security context, labels, annotations, etc. 
As we discussed earlier with @verb, we need to extend debug command profiling with custom profiling ability in addition to static profiles. This feature can be tracked in https://github.com/kubernetes/enhancements/issues/1441. 

I'm closing this issue.

/close

**Closed by ardaguclu** 2023-05-18 11:08 UTC
Labels: kind/feature, sig/cli, needs-triage
