### ISSUE TITLE
Failed to get terminated pod logs

### ISSUE THREAD

**Issue by zr-mah** [kubernetes/kubectl#1622] opened 2024-07-09 03:16 UTC
**What happened**:
I couldn't query any terminated pod's logs recently. (I still finding out when it first started at which version)

**What you expected to happen**:
I'm expecting to get the logs for all the terminated pods.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start a pod
2. Able to get logs using `kubectl logs -n xx pod_name`
3. Pass in previous parameter (-p) before terminating, expected to get 'previous terminated container xx in pod xx not found'
4. Terminate the pod and wait for a few seconds
5. Get logs with previous parameter passed in expected to get logs but instead getting pods not found.

**Anything else we need to know?**:

**Environment**:
kubectl version

Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.16-eks-3af4770

Attached image with the chronological order
![kubectl_sequence](https://github.com/kubernetes/kubectl/assets/23479560/100c8c12-d7aa-41ca-8c63-e6732fb01a80)

**Comment by ardaguclu** [comment] 2024-07-09 08:01
It is a duplicate of https://github.com/kubernetes/kubectl/issues/1588

**Comment by zr-mah** [comment] 2024-07-09 09:20
Hi @ardaguclu, the reporter for that issue is expecting to skip the pod not found error. 

However for this issue. the pod not found is not expected to happen.

**Comment by ardaguclu** [comment] 2024-07-09 10:58
Previous flag's desription https://github.com/kubernetes/kubectl/blob/a6de79e3d40575480caa71a8e5efffeea6587251/pkg/cmd/logs/logs.go#L176:

```
If true, print the logs for the previous instance of the container in a pod if it exists.
```
If the container does not exist, there is nothing we can do in here. This issue and https://github.com/kubernetes/kubectl/issues/1588 are both trying to overcome this in a different way but the same thing. If container does not exist, kubectl can not get any logs. I think, this is the expected behavior.

**Comment by zr-mah** [comment] 2024-07-09 11:14
Hi @ardaguclu, thanks for helping but for this issue the pod shouldn't be missing at the first place.

As the parameter description mentioned. It should get terminated logs.

This issue is not related to ignore all errors flag too.

**Comment by ardaguclu** [comment] 2024-07-09 11:21
Is the issue "kubectl logs command can't get logs from terminated pod" or "why the pod xx is terminated"?

> 3. Pass in previous parameter (-p) before terminating, expected to get 'previous terminated container xx in pod xx not found'
why we are expecting to get "not found" error

> 5. Get logs with previous parameter passed in expected to get logs but instead getting pods not found.
The pod is terminated and kubectl logs can't get logs anymore, what is the expectation in here different than my comment in https://github.com/kubernetes/kubectl/issues/1622#issuecomment-2217330409

**Comment by zr-mah** [comment] 2024-07-09 12:57
Hi @ardaguclu 
In #1588, the reporter was saying
> "I was expecting the --ignore-errors would skip such messages from the output. Is there a way to achieve that?"

To answer your question

1. This issue is about "kubectl logs command can't get logs from terminated pod"
2. If the container hasn't been terminated and passing the -p flag. getting `previous terminated container xx in pod xx not found` is expected.
3. The issue is that the container existed. that is why it is not expected.

Could you have a look at the screenshot? I showed the steps to further prove that the container was there before i do termination.

**Comment by mpuckett159** [comment] 2024-07-17 16:17
The screenshot doesn't show how the pod was terminated, and between which lines of "no previously terminated containers" the pod termination command was run, so it is not clear to me from this screenshot what exactly is happening. I suspect that as soon as the container is terminated (and thus available for the `-p` command) the pod is then terminated and you then need to go to find pod termination logs instead. If you look [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#container-v1-core) in the `terminationMessagePath` field you'll see that pod termination logs are written to `/dev/termination-log` on the node it is running on by default.

/close

**Closed by mpuckett159** 2024-07-17 16:18 UTC
Labels: kind/bug, needs-triage
