### ISSUE TITLE
Wrong binary is downloaded for kubectl v1.17.15

### ISSUE THREAD

**Issue by subodh-dharma** [kubernetes/kubectl#1009] opened 2021-01-20 19:39 UTC
**What happened**:

Download kubectl binary from https://dl.k8s.io/release/v1.17.15/bin/linux/amd64/kubectl results in downloading kubectl for version 1.17.16-rc.0

**What you expected to happen**:

Expect to get kubectl binary for v1.17.15

**How to reproduce it (as minimally and precisely as possible)**:

Download the binary from https://dl.k8s.io/release/v1.17.15/bin/linux/amd64/kubectl 

```bash
curl -L https://dl.k8s.io/release/v1.17.15/bin/linux/amd64/kubectl --output kubectl11715

chmod +x kubectl11715

./kubectl11715 version
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.16-rc.0", GitCommit:"737e2c461a2999fa242d39e77b9252d0eee7167e", GitTreeState:"clean", BuildDate:"2020-12-09T11:14:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu

**Comment by dougsland** [comment] 2021-01-20 20:01
Indeed. I am not familiar how to fix the download/release area. @brianpursley  @eddiezane @pwittrock  might be familiar.
/triagge accept

**Comment by rikatz** [comment] 2021-01-20 20:21
/close

Duplicate of https://github.com/kubernetes/kubernetes/issues/97241 :)

**Closed** 2021-01-20 20:21 UTC
Labels: kind/bug, needs-triage
