### ISSUE TITLE
Improve output when a resource is requested from a non-existing namespace

### ISSUE THREAD

**Issue by Atish-iaf** [kubernetes/kubectl#1485] opened 2023-09-15 06:48 UTC
**What would you like to be added**:
When a namespace doesn't exist (say "xyz") and a resource is requested from this non-existing namespace("xyz"), it should return that namespace doesn't exist.
```
kubectl get pod -n xyz
No resources found in xyz namespace.  //----> It is misleading, instead it can return something like "Error from server (NotFound):namespaces "xyz" not found"
```

**Why is this needed**:

**Comment by ardaguclu** [comment] 2023-09-15 06:51
Thanks for opening this issue. But it seems that this is duplicate of https://github.com/kubernetes/kubectl/issues/1290 and the request was rejected due to https://github.com/kubernetes/kubectl/issues/1290#issuecomment-1276468256

I'd prefer closing this, since it has been already discussed a couple of times;
/close

**Closed by ardaguclu** 2023-09-15 06:51 UTC
Labels: kind/feature, needs-triage
