### ISSUE TITLE
Diff exit code is not helpful

### ISSUE THREAD

**Issue by steeling** [kubernetes/kubectl#765] opened 2019-11-11 23:54 UTC
kubectl diff returns an exit code of 1 on a valid diff, and on an actual error.

This would be more helpful if it followed the standard diff error codes:
    0     No differences were found. 
    1     Differences were found.
   >1     An error occurred.

**Comment by eddiezane** [comment] 2019-12-07 06:16
This looks like a duplicate of #707 which has an [open PR](https://github.com/kubernetes/kubernetes/pull/82336) :tada:.

**Comment by seans3** [comment] 2019-12-09 06:41
Closing, since it's a duplicate.

/close

**Closed by seans3** 2019-12-09 06:41 UTC
