### ISSUE TITLE
kubectl cp return error of "error: unexpected EOF" for copy files from Azure Kubernetes Service Windows container with "--retries" and "--request-timeout"

### ISSUE THREAD

**Issue by gengdade** [kubernetes/kubectl#1631] opened 2024-08-07 07:00 UTC
**What happened**:  **When trying copy big files/folders (for example , file larger than 500MB)  from Azure Kubernetes Service Windows c container, the command always return error:**

kubectl cp    mynamespace/windows-debug-12948:/x/a/   ./ -c windows-debug-12948
tar: Removing leading '/' from member names
Dropping out copy after 0 retries
error: unexpected EOF
 
**Then we tried use retries and request-timeout, got similarerror:**
 
 
  kubectl cp   --retries=1000 mynamespace/windows-debug-12948:/x/a/   ./ -c windows-debug-12948
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "b015d852bca6c565f22d51a229e013710b9e71ecd7f37a4dda04a9b6876f517a": failed to get application name from commandline "sh -c \"tar cf - /x/a | tail -c+0\"": failed to find executable "sh -c \"tar cf - /x/a | tail -c+0\"": unknown
 
kubectl cp    --request-timeout=10000m mynamespace/windows-debug-34135:/x/b/   ./ -c windows-debug-34135
tar: Removing leading '/' from member names
Dropping out copy after 0 retries
error: unexpected EOF

### **Why the kubectl looking for command sh and tail ? there is no such files on the windows container**

**What you expected to happen**:  copy exact file back without error.

**How to reproduce it (as minimally and precisely as possible)**:  prepare one big file (>500MB) on the windows container in Azure Kubernetes Service, try copy it back.  

**Anything else we need to know?**:

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: windows/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2024-04-12T23:21:51Z"
  compiler: gc
  gitCommit: 1c9860e7360c3f8147ae068e867eaab73b4a6257
  gitTreeState: clean
  gitVersion: v1.27.9
  goVersion: go1.20.12
  major: "1"
  minor: "27"
  platform: linux/amd64
- Cloud provider or hardware configuration: Azure Kubernetes SErvice
- OS (e.g: `cat /etc/os-release`):  Windows 2019

**Comment by ardaguclu** [comment] 2024-08-07 11:42
I think this is duplicate of https://github.com/kubernetes/kubernetes/issues/60140 and to better manage this issue, I'd prefer closing this one.

/close

**Closed by ardaguclu** 2024-08-07 11:42 UTC
Labels: kind/bug, needs-triage
