### ISSUE TITLE
`kubectl create secret` is missing the `--save-config` flag

### ISSUE THREAD

**Issue by lindhe** [kubernetes/kubectl#1512] opened 2023-10-27 16:23 UTC
**What happened**:

There is a `--save-config` flag for the `create` subcommand:

```console
$ kubectl create --help
[…]
Options:
[…]
    --save-config=false:
        If true, the configuration of current object will be saved in its annotation. Otherwise, the annotation will
        be unchanged. This flag is useful when you want to perform kubectl apply on this object in the future.
[…]
```

It works for most object types, but not `secret`:

```console
$ kubectl create --save-config configmap foo --dry-run=client -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"foo","creationTimestamp":null}}
  creationTimestamp: null
  name: foo

$ kubectl create --save-config secret generic foo --dry-run=client -o yaml
error: unknown flag: --save-config
See 'kubectl create secret --help' for usage.
```

**What you expected to happen**:

I expect the flag to work as documented.

**How to reproduce it (as minimally and precisely as possible)**:

```shell
kubectl create --save-config secret generic foo --dry-run=client -o yaml
```

**Environment**:

```console
$ kubectl version --client --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.7
Kustomize Version: v4.5.7
```

**Comment by gameduser** [comment] 2023-10-29 18:25
Hi @lindhe I was able to reproduce your issue, but foun that if you switch the order this way [1] it works fine. Let me know your outcome.

[1]:
`> kubectl create secret generic foo --save-config --dry-run=client -o yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"foo","creationTimestamp":null}}
  creationTimestamp: null
  name: foo`

**Comment by lindhe** [comment] 2023-10-30 08:41
Agreed, I get the same results.

For me, that have not looked into the code much, this sounds pretty strange. The `--save-config` flag is documented as a flag to `create`, so putting that flag as an argument to `create secret` is surprising.

**Comment by ardaguclu** [comment] 2023-10-30 09:23
The order matters in spf13/cobra. kubectl first needs to identify the command `create configmap`, `create secret` , etc.. And after that flags (i.e. `--save-config`) should be added. If flags are added between create and configmap, that breaks the identification of command. Even though, command is identified successfully, that results in the ignorance of `--save-config`. 

I'd prefer closing this as not a bug.

**Comment by lindhe** [comment] 2023-10-30 09:35
If that had consistently been the case, I would agree that this is not a bug. But it seems like `kubectl create secrets` behave differently w.r.t. this compared to other `kubectl create x` commands. I believe that there is a bug somewhere here, that makes `create secret` behave differently than (all?) other `create` subcommands.

And if the flag should indeed go _after_ `x` in `kubectl create x`, not before it, I think the documentation (particularly the `--help` texts) should reflect that. As it stands, `kubectl create --help` shows `--save-config` as a flag, implying that `kubectl create` takes the flag.

**Comment by ardaguclu** [comment] 2023-11-03 07:06
I investigated this issue;

First task of cobra is to find the correct command being executed. `kubectl create --save-config configmap` and `kubectl create configmap --save-config` are equivalent because there is no other command creating any ambiguity. cobra successfully continues other executions by assuming that the command is `create configmap`.

On the other hand, `kubectl create secret --any-flag generic`(or `kubectl create --any-flag secret generic`) is not equivalent to `kubectl create secret generic --any-flag` because for the former, cobra detects `create secret` as command(be aware not `create secret generic`) which doesn't have any `--save-config` flag and for the latter, it detects `create secret generic` which has `--save-config` command.

I understand the inconvenience in here. But suggested way is to use flags after the commands;

```sh
kubectl create secret generic --save-config foo --dry-run=client -oyaml
```

I'd prefer closing this as it works as intended. 

/close

**Closed by ardaguclu** 2023-11-03 07:06 UTC
Labels: kind/bug, needs-triage

**Comment by lindhe** [comment] 2023-11-03 07:11
Thank you for the explanation. It makes more sense to me now. Is it possible to remove it from `kubectl config --help` since it should not be used as a flag for that command?
