### ISSUE TITLE
kubectl wait-for cannot handle JSON path filter expressions like ?(@.x==y)

### ISSUE THREAD

**Issue by andreaskaris** [kubernetes/kubectl#1448] opened 2023-07-10 16:17 UTC
### What happened?

kubectl wait-for cannot handle JSON path filter expressions like ?(@.x==y)

See https://github.com/kubernetes/kubectl/issues/1224#issuecomment-1560856195
~~~
Even without ||, using ?(x==y) fails to parse, due to this split on =:

Line 208 in [838ae9f](https://github.com/kubernetes/kubectl/commit/838ae9fd9ec21c92d9ad690a902bbbd459f98ee4)
 splitStr := strings.Split(condition, "=")
~~~

### What did you expect to happen?

Do not split the string on '==' and only on '=' so that JSON path filter expressions are handled correctly

### How can we reproduce it (as minimally and precisely as possible)?

The following will fail, yet it should work:
~~~
kubectl wait --for='jsonpath={.status.conditions[?(@.type=="Ready")].status}=True' pod/busybox1
~~~

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mpuckett159** [comment] 2023-07-19 16:12
/close
Duplicate of issue [here](https://github.com/kubernetes/kubectl/issues/1259)
Please track this issue there. There is a PR to fix this [here](https://github.com/kubernetes/kubernetes/pull/111461)

**Closed by mpuckett159** 2023-07-19 16:12 UTC
Labels: kind/bug, sig/cli, needs-triage
