### ISSUE TITLE
Confusing `kubectl rollout status` message

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubectl#760] opened 2019-11-07 06:26 UTC
Can anyone explain what does the "to complete 0 pods" and "to complete 1 pods" mean? What's the status of the pod and/or Statefulset when this message is printed out at the console and how does it relate to the following 2 lines of console output "Waiting for 1 pods to be ready..."???
```
$ kubectl rollout status sts rateapiservice
waiting for statefulset rolling update to complete 0 pods at revision rateapiservice-55ff8f6b54...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
waiting for statefulset rolling update to complete 1 pods at revision rateapiservice-55ff8f6b54...
Waiting for 1 pods to be ready...
Waiting for 1 pods to be ready...
statefulset rolling update complete 2 pods at revision rateapiservice-55ff8f6b54...
```
```
 k version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6-eks-5047ed", GitCommit:"5047edce664593832e9b889e447ac75ab104f527", GitTreeState:"clean", BuildDate:"2019-08-21T22:32:40Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by seans3** [comment] 2020-01-22 17:57
Please note: the version skew you report is NOT supported (client 1.16; server 1.14; we only support versions +/- 1 version). Please reproduce this using an appropriate version.

/sig cli
/area kubectl
/kind bug
/priority P2

**Comment by soltysh** [comment] 2020-02-19 17:54
Closing due to age, feel free to re-open if you get more insights. 
/close

**Closed by soltysh** 2020-02-19 17:54 UTC
Labels: area/kubectl, kind/bug, priority/P2, sig/cli
