### ISSUE TITLE
Confusing formatting when printing memory requests/limits for pod with multiple containers

### ISSUE THREAD

**Issue by struffel** [kubernetes/kubectl#1410] opened 2023-04-14 08:24 UTC
**What happened**:
I wanted to print the memory requests/limits for all pods in a namespace, using this command/script:

```
# Modified version of https://stackoverflow.com/a/73190962
# Application name changed for privacy
ns='NAMESPACE:.metadata.namespace'
pod="POD:.metadata.name"
container='CONTAINER:.spec.containers[*].name'
resource_req_mem='MEM_REQ:.spec.containers[*].resources.requests.memory'
resource_lim_mem='MEM_LIM:.spec.containers[*].resources.limits.memory'

kubectl get pod  -n my-namespace -o custom-columns="$ns,$pod,$container,$resource_req_mem,$resource_lim_mem"
```

It produced this output:

```
NAMESPACE           POD                 CONTAINER                      MEM_REQ      MEM_LIM
my-namespace        my-app              my-app-container,istio-proxy   48Mi,128Mi   1Gi
```

It is impossible to tell which container has which memory *limit*. In this case looking at the YAML reveals that the `1Gi` actually refer to the `istio-proxy` container whereas `my-app-container` runs with no limit at all, only a `requests: 48Mi` declaration.

**What you expected to happen**:

Kubectl already responds with `<None>` if no limit/request is set for any container in the Pod, I think this could be applied in a per-container way when concatenating the values into a string for printing , so that the output looks like this:
```
NAMESPACE           POD                 CONTAINER                      MEM_REQ      MEM_LIM
my-namespace        my-app              my-app-container,istio-proxy   48Mi,128Mi   <None>,1Gi
```
That would make the output a lot less confusing.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a deployment with one pod containing two containers
- Give the first container a memory request, but no limit
- Give the second container both a memory request and a limit
- Run the script snipped above in the corresponding namespace and observe the output

**Anything else we need to know?**:

This is possibly related to #1385 .

**Environment**:
- Kubernetes client and server versions (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+1.el8", GitCommit:"b2dac3c284a7435be72c9424ee03acdca731b59f", GitTreeState:"clean", BuildDate:"2022-11-23T15:22:52Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+1.el8", GitCommit:"b2dac3c284a7435be72c9424ee03acdca731b59f", GitTreeState:"clean", BuildDate:"2022-11-23T15:33:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Oracle Cloud Native Environment 1.5
- OS (e.g: `cat /etc/os-release`):
```
NAME="Oracle Linux Server"
VERSION="8.7"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.7"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:7:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.7
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.7
```

**Comment by eddiezane** [comment] 2023-04-26 16:59
@brianpursley I think this is a duplicate of what we talked about a few weeks ago?

https://gist.github.com/brianpursley/41f0983012f18256938745beb5a4657c

**Comment by brianpursley** [comment] 2023-04-27 01:31
> @brianpursley I think this is a duplicate of what we talked about a few weeks ago?
> 
> https://gist.github.com/brianpursley/41f0983012f18256938745beb5a4657c

Yes.

It is unintuitive because while containers set limits, they affect the pod. Surprisingly, if one container sets a limit and another does not, the pod ignores the unlimited container and uses the limit set on the one container as it's limit.

See this PR where I confirm this is so.
https://github.com/kubernetes/kubernetes/pull/117171#issuecomment-1504245993

In light of this, I'm not sure if showing the limits this way would be helpful.

If you really need to get the limits set by the containers, then maybe the pod's json could be parsed to extract this information, but it really doesn't reflect how the pod actually uses those limits.

**Comment by ardaguclu** [comment] 2023-05-18 11:00
As far as I can see this is known and works as expected. 
I'd prefer closing this issue. Feel free to re-open it, if you think I'm missing something. Thanks.

/close

**Closed by ardaguclu** 2023-05-18 11:00 UTC
Labels: kind/bug, needs-triage
