### ISSUE TITLE
403 Forbidden error downloading the binary

### ISSUE THREAD

**Issue by drgroot** [kubernetes/kubectl#1473] opened 2023-08-21 03:45 UTC
**What happened**:

Unable to download kubectl,
`curl https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl` gave 403. HTTP Error 403: Forbidden

**What you expected to happen**:

Download the binary. This is not an issue from other sites, such as github, dockerhub, etc.

**How to reproduce it (as minimally and precisely as possible)**:
`curl https://dl.k8s.io/release/v1.27.1/bin/linux/amd64/kubectl`

**Anything else we need to know?**:

**Environment**:
Trying from a bunch of OVH VPS servers

IPs:

* 51.79.84.120
* 142.44.163.21

**Comment by ardaguclu** [comment] 2023-09-01 11:20
I'm not sure what this url refers to or who manages this. Could you please provide the documentation about this url?. On the other hand, this is clearly not a bug in kubectl and I'm closing this. Would be better to open a separate issue on kubernetes repo.

/close

**Closed by ardaguclu** 2023-09-01 11:20 UTC
Labels: kind/bug, needs-triage
