### ISSUE TITLE
kubectl complete error: command not found: __debug

### ISSUE THREAD

**Issue by feiskyer** [kubernetes/kubectl#353] opened 2018-03-14 05:42 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

When using kubectl with autocomplete, e.g. `kubectl create -f nginx <TAB>`, then there is `command not found: __debug` error reported:

```sh
kubectl create -f ng__kubectl_filedir:3: command not found: __debug
__kubectl_filedir:20: command not found: __debug
inx
```

kubectl version: v1.10.0-alpha.3.1792+891b471064ddc1.

**What you expected to happen**:

kubectl should autocomplete with no errors.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by seans3** [comment] 2018-03-14 17:49
This issue is a duplicate of: 
https://github.com/kubernetes/kubernetes/issues/60517
https://github.com/kubernetes/kubernetes/issues/61017

This issue has been fixed yesterday (3/13/2018): https://github.com/kubernetes/kubernetes/pull/61129

It is being cherry-picked into 1.10 release

**Comment by feiskyer** [comment] 2018-03-15 01:47
@seans3 Cool. Thanks

**Closed** 2018-03-15 01:48 UTC
Labels: kind/bug
