### ISSUE TITLE
kubectl taint nodes command has wrong examples

### ISSUE THREAD

**Issue by gavinfish** [kubernetes/kubectl#811] opened 2020-01-31 06:10 UTC
```
shenjie@Shens-MacBook-Pro kubernetes % kubectl taint nodes -h
Update the taints on one or more nodes.
...
 
  # Add to node 'foo' a taint with key 'bar' and no value
  kubectl taint nodes foo bar:NoSchedule

```

In the `kubectl taint nodes` command help information, the `bar:NoSchedule` argument should be ` bar=:NoSchedule`, otherwise it will throw error like this:

```
shenjie@Shens-MacBook-Pro kubernetes % kubectl taint nodes aks-agentpool-18072580-0 bar:NoSchedule
error: at least one taint update is required
```

## Environment
```
shenjie@Shens-MacBook-Pro kubernetes % brew list kubernetes-cli --versions
kubernetes-cli 1.17.2

shenjie@Shens-MacBook-Pro kubernetes % kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

```

Ref: kubernetes/website#18874
/assign

**Comment by soltysh** [comment] 2020-02-14 14:29
Duplicate of https://github.com/kubernetes/kubernetes/issues/87296.
/close

**Closed by soltysh** 2020-02-14 14:29 UTC
