### ISSUE TITLE
"kubectl create job --from=cronjob/hello hello-job" fails with "error: failed to create job: jobs.batch "hello-job" is forbidden: cannot set blockOwnerDeletion..."

### ISSUE THREAD

**Issue by syedriko** [kubernetes/kubectl#842] opened 2020-03-17 22:55 UTC
**Kubernetes version (use kubectl version):**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
$
```

**Environment:**
```
$ cat /etc/redhat-release 
Fedora release 31 (Thirty One)
$ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1
$ 
```

**What happened:**
```
$ kubectl create job --from=cronjob/hello hello-job
error: failed to create job: jobs.batch "hello-job" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion apps/v1 Kind CronJob: no matches for kind "CronJob" in version "apps/v1"
$
```

**What you expected to happen:**
```
$ kubectl create job --from=cronjob/hello hello-job
job.batch/hello-job created
$
```

**How to reproduce:**

1. enable the OwnerReferencesPermissionEnforcement API server admission plugin

1. create a CronJob, the one from the k8s docs will do:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "30 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from a CronJob
          restartPolicy: OnFailure
```
1. Run "kubectl create job":
```
$ kubectl create job --from=cronjob/hello hello-job
error: failed to create job: jobs.batch "hello-job" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion apps/v1 Kind CronJob: no matches for kind "CronJob" in version "apps/v1"
$
```
- Disable the OwnerReferencesPermissionEnforcement admission plugin, repeat the "create job" command that now succeeds and examine metadata.ownerReferences, which refers to {apiVersion: **apps/v1**, kind: CronJob} but needs to be {apiVersion: **batch/v1beta1**, kind: CronJob} instead:
```
$ kubectl get job.batch/hello-job -oyaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  creationTimestamp: "2020-03-17T17:46:12Z"
  labels:
    controller-uid: 1a1375bb-cf92-433c-b2ca-74caf8d37c71
    job-name: hello-job
  name: hello-job
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: CronJob
    name: hello
    uid: 38bc1133-075f-4e63-8f33-55d5cbd61cf8
  resourceVersion: "1538"
  selfLink: /apis/batch/v1/namespaces/default/jobs/hello-job
  uid: 1a1375bb-cf92-433c-b2ca-74caf8d37c71
...
```

**Comment by soltysh** [comment] 2020-03-18 17:05
Duplicate of https://github.com/kubernetes/kubernetes/issues/88645
/close

**Closed by soltysh** 2020-03-18 17:05 UTC
