### ISSUE TITLE
Allow adding a custom header to kubectl API calls from the command line

### ISSUE THREAD

**Issue by MarcPow** [kubernetes/kubectl#1463] opened 2023-08-11 17:00 UTC
**What would you like to be added**:

Support kubectl --request-header "X-Custom-Header: custom-value"

**Why is this needed**:

I imagine there are a variety of scenarios that would be useful.

The one that I'm thinking about: it's often useful to stand up a transparent reverse proxy for the api-server that can inspect a custom header and then route traffic as needed to one or more clusters.

This command-line parameter would be used to 

Such proxies allow for:
- policy-based traffic inspection that add defense in depth
- various types of logical network segmentation.

**Comment by ardaguclu** [comment] 2023-08-15 12:35
I think, this is duplicate of https://github.com/kubernetes/kubectl/issues/1352 and that would be better to close this issue to unify the discussions.

**Comment by mpuckett159** [comment] 2023-08-16 23:54
/close
This issue will be moved to https://github.com/kubernetes/kubectl/issues/1352 as it has historical discussion.

**Closed by mpuckett159** 2023-08-16 23:54 UTC
Labels: kind/feature, needs-triage
