### ISSUE TITLE
Autocomplete issues with --from-file and --from-literal

### ISSUE THREAD

**Issue by bkrannich** [kubernetes/kubectl#121] opened 2017-11-06 10:02 UTC
**Kubernetes version** (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"dirty", BuildDate:"2017-10-17T15:09:55Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: minikube
- **OS** (e.g. from /etc/os-release): macOS Sierra, 10.12.6
- **Kernel** (e.g. `uname -a`): `Darwin WDFM31654402A 16.7.0 Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT 2017; root:xnu-3789.71.6~1/RELEASE_X86_64 x86_64`
- **Install tools**: n/a
- **Others**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)`

**What happened**:
I was following along the Kubernetes Up & Running book and found that autocomplete for some of the configmaps and secrets examples doesn't work as expected.

**What you expected to happen**:
I was expecting the autocomplete to work for the `--from-file` and `--from-literal` parameters, however, I got some bash errors.

**How to reproduce it** (as minimally and precisely as possible):
* Type:
```
kubectl create configmap my-config --from-file=<tab>
```
Result:
```
kubectl create configmap my-config --from-file=--from-file= (instead of a list of files in the local directory)
```
* Type:
```
kubectl create configmap my-config --from-file=my-config.txt --from-li<tab>
```
Result (my-config.txt should of course exist in the local directory):
```
kubectl create configmap my-config --from-file=my-config.txt --from-li-bash: --from-file=: syntax error: operand expected (error token is "=")
```

Similar behavior for `kubectl create secret`.

**Comment by superbrothers** [comment] 2017-11-09 06:32
This issue seems to be already fixed in cobra by https://github.com/spf13/cobra/pull/415.

**Comment by apelisse** [comment] 2017-12-01 16:59
Yeah, can someone verify if this is fixed on a more recent kubectl? Thanks

**Comment by shiywang** [comment] 2017-12-06 03:02
@apelisse we can verify this once that update vendor spf13/cobra pr merged which is after 1.9 release I guess ?

**Comment by apelisse** [comment] 2017-12-06 04:31
One could check-out the master branch, merge that PR locally, compile kubectl and see if it is fixed.

**Comment by shiywang** [comment] 2017-12-06 07:34
yes, we can do that beforehand, but we will merge that anyway since it not only fix this issue but also the others, so how about test it after merge.

**Comment by superbrothers** [comment] 2017-12-08 20:26
I merged spf13/cobra#415 into the master branch (https://github.com/superbrothers/kubernetes/commit/7a7e11459f0ffe3873b13d410a5e76f65db07e17) and verified this issue is fixed, but @shiywang is right, we should verify again after https://github.com/kubernetes/kubernetes/pull/53631 will be merged.

**Comment by shiywang** [comment] 2018-01-18 12:34
@bkrannich  I think this should been fixed, would you like to try it again on master branch ?

**Comment by bkrannich** [comment] 2018-01-19 17:30
@shiywang: I tried but couldn't verify the fix is working. However, this might be due to the fact that I'm pretty new to the topic. Let me describe the steps I followed so that you can maybe point me to where I did something wrong:

* Synced to https://github.com/kubernetes/kubernetes/commit/49c729eef41ef09b2c3a04376bfa81846faed9ca
* Ran the build via `make`
* What I got was:
```
kubernetes/_output/bin# ./kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0-alpha.1.1080+49c729eef41ef0", GitCommit:"49c729eef41ef09b2c3a04376bfa81846faed9ca", GitTreeState:"clean", BuildDate:"2018-01-19T09:45:25Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"darwin/amd64"}
Unable to connect to the server: Forbidden
```
* To activate the latest auto-complete, I did (as just sourcing it directly didn't work on my Mac, see #37)
```
./kubectl completion bash > kubectl.source_me
source kubectl.source_me
```
* Then, I ran the commands I provided initially, but got the same results:
```
# just to make sure the correct kubectl is taken
export PATH=$(pwd)

kubectl create configmap my-config --from-file=<tab>
kubectl create configmap my-config --from-file=my-config.txt --from-li<tab>
```

**Comment by apelisse** [comment] 2018-01-19 17:54
I tried in december, it wasn't working. No surprise to me.

**Comment by superbrothers** [comment] 2018-01-19 23:07
I also tried but it wasn't working on bash 3.2. However it was working on bash 3.4. @shiywang Please reopen this issue.

**Comment by superbrothers** [comment] 2018-01-20 07:35
Finally I found the cause of this problem and it will be fixed by https://github.com/spf13/cobra/pull/520. I verified as follows:

```
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
$ pwd
/Users/ksuda/src/k8s.io/kubernetes
$ git checkout 49c729e
HEAD is now at 49c729eef4... Merge pull request #58501 from bowei/cp-zones
$ curl -s -L https://github.com/spf13/cobra/pull/520.diff | patch vendor/github.com/spf13/cobra/bash_completions.go
patching file vendor/github.com/spf13/cobra/bash_completions.go
can't find file to patch at input line 325
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/bash_completions_test.go b/bash_completions_test.go
|index 071a6a2a..4280294a 100644
|--- a/bash_completions_test.go
|+++ b/bash_completions_test.go
--------------------------
File to patch:
Skip this patch? [y] y
Skipping patch.
1 out of 1 hunk ignored
$ go build -o _output/bin/kubectl cmd/kubectl/kubectl.go

# If you haven't installed bash-completion
$ brew install bash-completion
$ . /usr/local/etc/bash_completion

$ _output/bin/kubectl completion bash > completion.bash
$ source completion.bash                                                                                         2
# It works properly
$ kubectl create configmap my-config --from-file=config.txt --from-literal=
```

**Closed** 2018-02-04 16:42 UTC
Labels: bug
