### ISSUE TITLE
Bash completion is broken for aliases that contain a flag

### ISSUE THREAD

**Issue by droslean** [kubernetes/kubectl#1466] opened 2023-08-15 12:24 UTC
This works:
```console
alias k='kubectl'
complete -o default -F __start_kubectl k
```

This doesn't work
```console
alias k='kubectl --kubeconfig my_config'
complete -o default -F __start_kubectl k
```

I am trying to figure out why, and if this is related to my Fedora or its a bug in the kubectl bash completion script.

```console
$ k por+ local cur prev words cword split
+ COMPREPLY=()
+ declare -F _init_completion
+ _init_completion -n =:
+ local exclude= flag outx errx inx OPTIND=1
+ getopts n:e:o:i:s flag -n =:
+ case $flag in
+ exclude+==:
+ getopts n:e:o:i:s flag -n =:
+ COMPREPLY=()
+ local 'redir=@(?([0-9])<|?([0-9&])>?(>)|>&)'
+ _get_comp_words_by_ref -n '=:<>&' cur prev words cword
+ local exclude flag i OPTIND=1
+ words=()
+ local cur cword words
+ upargs=()
+ upvars=()
+ local upargs upvars vcur vcword vprev vwords
+ getopts c:i:n:p:w: flag -n '=:<>&' cur prev words cword
+ case $flag in
+ exclude='=:<>&'
+ getopts c:i:n:p:w: flag -n '=:<>&' cur prev words cword
+ [[ 6 -ge 3 ]]
+ case ${!OPTIND} in
+ vcur=cur
+ (( OPTIND += 1 ))
+ [[ 6 -ge 4 ]]
+ case ${!OPTIND} in
+ vprev=prev
+ (( OPTIND += 1 ))
+ [[ 6 -ge 5 ]]
+ case ${!OPTIND} in
+ vwords=words
+ (( OPTIND += 1 ))
+ [[ 6 -ge 6 ]]
+ case ${!OPTIND} in
+ vcword=cword
+ (( OPTIND += 1 ))
+ [[ 6 -ge 7 ]]
+ __get_cword_at_cursor_by_ref '=:<>&' words cword cur
+ words=()
+ local cword words
+ __reassemble_comp_words_by_ref '=:<>&' words cword
+ local exclude i j line ref
+ [[ -n =:<>& ]]
+ exclude='[=:<>&]'
+ printf -v cword %s 1
+ [[ -v exclude ]]
+ line='k por'
+ (( i = 0, j = 0 ))
+ (( i < 2 ))
+ [[ 0 -gt 0 ]]
+ ref='words[0]'
+ printf -v 'words[0]' %s k
+ line=' por'
+ (( i == COMP_CWORD ))
+ (( i++, j++ ))
+ (( i < 2 ))
+ [[ 1 -gt 0 ]]
+ [[ por == +([=:<>&]) ]]
+ ref='words[1]'
+ printf -v 'words[1]' %s por
+ line=
+ (( i == COMP_CWORD ))
+ printf -v cword %s 1
+ (( i++, j++ ))
+ (( i < 2 ))
+ (( i == COMP_CWORD ))
+ local i cur= index=5 'lead=k por'
+ [[ 5 -gt 0 ]]
+ [[ -n k por ]]
+ [[ -n kpor ]]
+ cur='k por'
+ (( i = 0 ))
+ (( i <= cword ))
+ [[ 5 -ge 1 ]]
+ [[ k != \k ]]
+ (( i < cword ))
+ local old_size=5
+ cur=' por'
+ local new_size=4
+ (( index -= old_size - new_size ))
+ (( ++i ))
+ (( i <= cword ))
+ [[ 4 -ge 3 ]]
+ [[  po != \p\o\r ]]
+ cur=por
+ (( index > 0 ))
+ (( index-- ))
+ [[ 3 -ge 3 ]]
+ [[ por != \p\o\r ]]
+ (( i < cword ))
+ (( ++i ))
+ (( i <= cword ))
+ [[ -n por ]]
+ [[ ! -n por ]]
+ (( index < 0 ))
+ local words cword cur
+ _upvars -a2 words k por -v cword 1 -v cur por
+ (( 10 ))
+ (( 10 ))
+ case $1 in
+ [[ -n 2 ]]
+ printf %d 2
+ [[ -n words ]]
+ unset -v words
+ eval 'words=("${@:3:2}")'
++ words=("${@:3:2}")
+ shift 4
+ (( 6 ))
+ case $1 in
+ [[ -n cword ]]
+ unset -v cword
+ eval 'cword="$3"'
++ cword=1
+ shift 3
+ (( 3 ))
+ case $1 in
+ [[ -n cur ]]
+ unset -v cur
+ eval 'cur="$3"'
++ cur=por
+ shift 3
+ (( 0 ))
+ [[ -v vcur ]]
+ upvars+=("$vcur")
+ upargs+=(-v $vcur "$cur")
+ [[ -v vcword ]]
+ upvars+=("$vcword")
+ upargs+=(-v $vcword "$cword")
+ [[ -v vprev ]]
+ [[ 1 -ge 1 ]]
+ upvars+=("$vprev")
+ upargs+=(-v $vprev "${words[cword - 1]}")
+ [[ -v vwords ]]
+ upvars+=("$vwords")
+ upargs+=(-a${#words[@]} $vwords ${words+"${words[@]}"})
+ (( 4 ))
+ local cur cword prev words
+ _upvars -v cur por -v cword 1 -v prev k -a2 words k por
+ (( 13 ))
+ (( 13 ))
+ case $1 in
+ [[ -n cur ]]
+ unset -v cur
+ eval 'cur="$3"'
++ cur=por
+ shift 3
+ (( 10 ))
+ case $1 in
+ [[ -n cword ]]
+ unset -v cword
+ eval 'cword="$3"'
++ cword=1
+ shift 3
+ (( 7 ))
+ case $1 in
+ [[ -n prev ]]
+ unset -v prev
+ eval 'prev="$3"'
++ prev=k
+ shift 3
+ (( 4 ))
+ case $1 in
+ [[ -n 2 ]]
+ printf %d 2
+ [[ -n words ]]
+ unset -v words
+ eval 'words=("${@:3:2}")'
++ words=("${@:3:2}")
+ shift 4
+ (( 0 ))
+ _variables
+ [[ por =~ ^(\$(\{[!#]?)?)([A-Za-z0-9_]*)$ ]]
+ [[ por =~ ^(\$\{[#!]?)([A-Za-z0-9_]*)\[([^]]*)$ ]]
+ [[ por =~ ^\$\{[#!]?[A-Za-z0-9_]*\[.*]$ ]]
+ case ${prev-} in
+ return 1
+ [[ por == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ [[ k == @(?([0-9])<|?([0-9&])>?(>)|>&) ]]
+ local i skip
+ (( i = 1 ))
+ (( i < 2 ))
+ [[ por == @(?([0-9])<|?([0-9&])>?(>)|>&)* ]]
+ (( i++ ))
+ (( 1 ))
+ (( i < 2 ))
+ (( cword <= 0 ))
+ prev=k
+ [[ -n '' ]]
+ return 0
+ __kubectl_debug
+ [[ -n '' ]]
+ __kubectl_debug '========= starting completion logic =========='
+ [[ -n '' ]]
+ __kubectl_debug 'cur is por, words[*] is k por, #words[@] is 2, cword is 1'
+ [[ -n '' ]]
+ words=("${words[@]:0:$cword+1}")
+ __kubectl_debug 'Truncated words[*]: k por,'
+ [[ -n '' ]]
+ local out directive
+ __kubectl_get_completion_results
+ local requestComp lastParam lastChar args
+ args=("${words[@]:1}")
+ requestComp='k __complete por'
+ lastParam=por
+ lastChar=r
+ __kubectl_debug 'lastParam por, lastChar r'
+ [[ -n '' ]]
+ '[' -z por ']'
+ [[ por == -*=* ]]
+ __kubectl_debug 'Calling k __complete por'
+ [[ -n '' ]]
++ eval 'k __complete por'
+ out=
+ directive=
+ out=
+ '[' '' = '' ']'
+ directive=0
+ __kubectl_debug 'The completion directive is: 0'
+ [[ -n '' ]]
+ __kubectl_debug 'The completions are: '
+ [[ -n '' ]]
+ __kubectl_process_completion_results
+ local shellCompDirectiveError=1
+ local shellCompDirectiveNoSpace=2
+ local shellCompDirectiveNoFileComp=4
+ local shellCompDirectiveFilterFileExt=8
+ local shellCompDirectiveFilterDirs=16
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ completions=()
+ local completions
+ activeHelp=()
+ local activeHelp
+ __kubectl_extract_activeHelp
+ local 'activeHelpMarker=_activeHelp_ '
+ local endIndex=13
+ IFS=
+ read -r comp
++ printf '%s\n' ''
+ '[' '' = '_activeHelp_ ' ']'
+ completions+=("$comp")
+ IFS=
+ read -r comp
+ '[' 0 -ne 0 ']'
+ '[' 0 -ne 0 ']'
+ __kubectl_handle_completion_types
+ __kubectl_debug '__kubectl_handle_completion_types: COMP_TYPE is 9'
+ [[ -n '' ]]
+ case $COMP_TYPE in
+ __kubectl_handle_standard_completion_case
+ local 'tab=	' comp
+ [[ '' != *	* ]]
+ IFS='
'
+ read -ra COMPREPLY -d ''
++ compgen -W '' -- por
+ return 0
+ __kubectl_handle_special_char por :
+ local comp=por
+ local char=:
+ [[ por == *:* ]]
+ __kubectl_handle_special_char por =
+ local comp=por
+ local char==
+ [[ por == *=* ]]
+ '[' 0 -ne 0 ']'

```

Version
```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6+6bf3f75", GitCommit:"cbbd0bdba10e0b612e32cdeb6462daa6909df4be", GitTreeState:"clean", BuildDate:"2023-08-09T09:50:58Z", GoVersion:"go1.19.10 X:strictfipsruntime", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ardaguclu** [comment] 2023-08-15 12:32
Thanks for opening this issue @droslean. This looks duplicate of https://github.com/kubernetes/kubectl/issues/1367 and therefore, I'm closing this. Feel free to re-open it, if you think I'm missing something.
/close

**Closed by ardaguclu** 2023-08-15 12:32 UTC
Labels: kind/bug, needs-triage
